language: node_js
node_js:
- '0.10'
- '0.11'
matrix:
  allow_failures:
  - node_js: '0.11'
env:
  global:
    - secure: "BjHGYTH+6+ZUj3Dc/kI8JGwoO54DkFiHsQmqNAEBUz9xeNQ7WeiWiCs4PiEaNQxAbalDcF4FBLNPWUDYV1T5U6FYax+qKeCrZcpdrWFTBoH2qUEjAIi+pVqLZxaKNgunW+MdUJLcGvhSPoNkEN/4c5CRgC9UdtaAh48RStm014M="
cache:
  directories:
  - node_modules
after_success:
  - "[[ $TRAVIS_BRANCH = 'master' ]] && [[ $TRAVIS_NODE_VERSION = '0.10' ]] && ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info"
